### ISSUE TITLE
property with "-" dash doesnt work in search? Or I am doing something wrong with stSearch

### ISSUE THREAD

**Issue by ginamdar** [lorenzofox3/Smart-Table#735]
I have json object as   
```[{"task-id":52,"task-priority":1,"task-name":"Modify Province","task-description":"","task-status":"InProgress"},...]  ```
and in html im rendering its as
```
<div class="widget-body" st-table="displayWorklist" st-safe-src="worklist"  >
<table class="table table-bordered table-striped table-condensed">
<thead>..</thead>
<tbody>
<tr ng-repeat="row in displayWorklist">
   <td class="text-center" >
   {{ row['task-id'] }}
  </td>
</table> ```  

Everything works fine, now when im trying to filter based on predicate as  
<th>
   <input st-search="'task-id'" placeholder="search for taskId"
  class="input-sm form-control" type="search"/>
  </th>  
```  
I get angular.js:10150 TypeError: $parse(...).assign is not a function

"angular": "~1.2",
angular-smart-table: "^2.1.8",

**Comment by ginamdar** [comment]
It seems that the solution is working with smart-table@1.4.8 not sure this is issue with angular or smart table now

**Comment by MrWook** [comment]
Hello @ginamdar,

The first problem is that you use ' in the st-search directive 
`<input st-search="task-id" placeholder="search for taskId"class="input-sm form-control" type="search"/>`

I guess the second problem is  a problem within angular. I never saw someone who use a parameter with "-" only with "_" like "task_id" or with a capital letter like "TaskId". And i think the reason behind it angular dont handle this kind of parameter when i used it in a ng-model i got an angular error.
So i think you need to change your parameter declaration.

Beside that it is a good idea to update your angular Version.

Altogether i don't know if im exactly right but that is how i could run your example without an error.

**Comment by ginamdar** [comment]
Hi @MrWook thank you for replying, 
1) yes i tried both way with and without single quote but didnt work. 
2) afaik the response which may not be as per JSON notation its coming from jbpm (Java Business Process Mgmt - kie-server ) which i have not control to change for now :(
3) I will soon be updating to 1.5 angular version to see if it magically works and will update here.
4) Meantime this is the [plunker ](http://plnkr.co/edit/fSeIZMHel45u0emdAKP7?p=preview )showing the same error in console and if you include this instead of smart-table-2.18.js 
<script src="smart-table.js"></script>  everything works fine.

**Comment by MrWook** [comment]
Hello @ginamdar,

the only thing how you really can fix it is by change the key name because in javascript you cant access a Object with a "-" in the name only a associative array. 
So you cant use: `$scope.task-id` but `$scope["task-id"]`.

So give you an understanding why the 1.4.8 version of SmartTable works i try to explain this to you.

The main different in the search directive of SmartTable is getting from:
` predicateObject[prop] = input;`
to
`$parse(prop).assign(predicateObject, input);`

So in the 1.4.8 the search key for example "task-id" is set to a key of an  associative array and get the entered value.
In 2.18 the input is parsed into a Object and like i said at the beginning you cant use a "-" in an Object.

Also it looks like the syntax for 1.4.8 is different because when you just change to 
`<script src="smart-table.js"></script>`
It starts a globals search. It never search for the object name "task-id".

Maybe you can try to change the key names on the javascript site like [plunker](http://plnkr.co/edit/dRDemk6j0qVriad59ECO?p=preview)

This is all i good sry if it doesn't help you out :s
