### ISSUE TITLE
Allow stSearch source value to be bound to a value instead of the input element

### ISSUE THREAD

**Issue by ppearcy** [lorenzofox3/Smart-Table#391]
I need to have my search box outside of my actual table. In order to facilitate this, I end up doing something like this when the input changes on my search box:

    public tableSearch(): void {
        var inputEvent = jQuery.Event('input', {
          target: {
            "value" : this.searchInput
          }});

        $('#smart-table-search-input').trigger(inputEvent);
      }

It'd be very nice to instead be able to bind the search value to scope variable and update the search as it changes as opposed to always being bound to an input element. 

I'd probably be able to make this update if it is something you're interested in including in the base.

**Comment by jvisser72** [comment]
Hi ppearcy,

This is already possible:

``` html
<section st-table="dataCollection" st-safe-src="actualData">
  <div class="row">
    <div class="col-md-3">
      <input st-search class="form-control" placeholder="FILTER" type="text"/>
    </div>
  </div>
  <br />
  <div class="row">
    <table class="table table-striped">
      <thead>
        <tr>
          <th st-sort="sortData1">Column 1</th>
          <th st-sort="sortData2">Column 2</th>
        </tr>
      </thead>
      <tbody>
        <tr ng-repeat="row in dataCollection">
          <td>row.sortData1</td>
          <td>row.sortData2</td>
        </tr>
      </tbody>
      <tfoot>
        <tr>
          <td colspan="2" class="text-center">
            <div st-pagination="" st-items-by-page="10" st-displayed-pages="5"></div>
          </td>
        </tr>
      </tfoot>
    </table>
  </div>
</section>
```

It would be nice though to apply filters to the dataCollection, for example filter on column data, without using an input. Currently I have a hidden input which filters on column data. When a button or tab-button is pressed the input data changes and the filter is applied.

**Comment by jvisser72** [comment]
Hi,

I have created a directive that can filter on a column.

``` javascript
/**
 * Created by Jeroen Visser on 30-04-15.
 * stFilter on column
 * <div stFilter="Columnname" filter="{{filterValue}}"></div>
 */

angular
    .module('myApp')
    .directive('stFilter', function () {
	return {
        require: '^stTable',
        link: function (scope, element, attr, ctrl) {
            var tableCtrl = ctrl;
            
            attr.$observe('stFilter', function (newValue, oldValue) 
            {
                var filter = attr.filter;
                if (newValue !== oldValue && filter) 
                	tableCtrl.search(filter, attr.stFilter || '');
            });
            
            scope.$watch(function () { return attr.filter; }, function (newValue, oldValue) {
            	if (newValue !== oldValue) 
            	{	var filter = newValue;
            		tableCtrl.search(filter, attr.stFilter || '');
            	}
            }, true);
        }
    };
});
```
Just use the directive in the section table example above as:

``` html
    <div class="col-md-3">
      <input st-search class="form-control" placeholder="FILTER" type="text"/>
      <div stFilter="sortData1" filter="{{filterValue}}"></div>
    </div>
```

Have fun with it. ;-)

**Comment by ppearcy** [comment]
Many thanks for the sample, that is exactly what I am trying to do. 

It'd be cool to see something like this pushed into the core, but am fine if this ticket is closed out to, since rolling your own isn't a big deal.

**Comment by dbkaplun** [comment]
:+1: awesome that you can do this! Would be good if this was documented.

**Comment by stefanmaric** [comment]
@jvisser72 I'm using your proposed `st-filter-column` and it gets the job done but `st-search` don't work.

I get the following console error every time the `st-search` input is updated:

```
TypeError: $parse(...).assign is not a function
    at StTableController.search
```

Using angular@1.3.16 and angular-smart-table@2.1.0

Any ideas on how to fix it?

Thanks!

**Comment by stefanmaric** [comment]
PD: it does work with angular-smart-table@2.0.3.

I see there are relevant changes on st-search from 2.0.3 to 2.1.0: https://github.com/lorenzofox3/Smart-Table/compare/v2.0.3...v2.1.1

But I'm not knowledgeable enough to properly update the `st-filter-column` directive.

**Comment by stefanmaric** [comment]
Trying to rewrite the directive based on stSearch code, I ended up with this:

```javascript
angula.module('myApp').directive('stSearchModel', [stSearchModel]);

function stSearchModel () {
  return {
    require: '^stTable',
    link: function (scope, element, attr, tableCtrl) {

      scope.$watch(attr.stSearchModel, function (newValue, oldValue) {
        if (newValue !== oldValue) {
          tableCtrl.search(newValue, attr.stPredicate);
        }
      });

      attr.$observe('stPredicate', function (newValue, oldValue) {
        var model = scope.$eval(attr.stSearchModel);
        if (newValue !== oldValue && model) {
          tableCtrl.search(model, newValue);
        }
      });
    }
  };
}
```

And got the very same error when triggering updates on `st-search` input.

Trying to debug it, I found that passing any predicate to `st-search` made it work smoothly with both the `stSearchModel` and `stFilterColumn` directives. So this works:

```html
<div class="col-md-3">
  <input st-search="$" class="form-control" placeholder="FILTER" type="text"/>
  <div st-filter-column="sortData1" filter-value="{{filterValue}}"></div>
</div>
```

But this doesn't:

```html
<div class="col-md-3">
  <input st-search class="form-control" placeholder="FILTER" type="text"/>
  <div st-filter-column="sortData1" filter-value="{{filterValue}}"></div>
</div>
```

Explicitly setting the predicate to "$" is not big deal, but not setting it at all should not be a problem. Any suggestions on how to workaround it from these directives?

Thanks.

**Comment by jvisser72** [comment]
Hi stefanmaric,

Sorry I didn't respond to your comment, I havn't watched this "closed" thread for a while ;-)
Strange thing is that it still works for me without explicitly using the st-search="$" notation.

I'm using smart-table V2.1.0 and agular V1.4.3 together with chrome V43.0.2357.134 m

Are there any other scripts that can cause this javascript error message?

Cheers.

**Comment by stefanmaric** [comment]
Hi @jvisser72,

I think the only other thing I'm doing is using `st-safe-src`. But I will take another look and I will try to isolate the issue in a fiddle later today and share it with you.

I forgot to thank you for your directive example and thank you for your attention.

Regards.

**Comment by stefanmaric** [comment]
You are damn right @jvisser72, it works perfectly (`smart-table@2.1.1` and `angular@1.4.3`):
http://embed.plnkr.co/KvtYP3TvuNtO84btPYZA/preview

After creating that plunker, I took a deeper look into the problematic project. The source of error was that an HTML compiler/checker was inserting `st-search="st-search"` when the `st-search` attribute was empty. What a fail.

Thanks for your attention. Regards.

**Comment by jvisser72** [comment]
Hi Stefanmaric,

Great news! have fun.

Cheers.
